### ISSUE TITLE
Cannot find module '@easydata/crud'  on the "dev" solution

### ISSUE THREAD

**Issue by pinale** [KorzhCom/EasyData#80]
downloading the repo and open the "EasyData.Dev.sln"  solution (i'd like to explore and debug the dev code)

i got this errors on build phase

`Error	TS2307	(TS) Cannot find module '@easydata/crud' or its corresponding type declarations.`
on the "EasyDataAspNetCoreTestXX" projects	

does i have to launch some client sctipt before build the server code ?

**Comment by korzh** [comment]
Hello,

Yes, it's better to run `setup_dev.bat` in the root folder to install all necessary NPM packages and add symlinks to @easydata packages inside node_modules where it's necessary. 

That is a Windows batch script but it mostly calls NPM commands so you can easily rewrite it (and the one in the `playground` folder) for Linux or Mac if necessary.

**Comment by pinale** [comment]
It works, thanks!
Now that i've the solution up and running, have i create the database manually or is there a script/command to generate it from the "EqDemo.zip" or from its json files

**Comment by korzh** [comment]
The database is created and seeded automatically on the first launch. We actually use [another our library (DbUtils)](https://github.com/KorzhCom/Korzh.DbUtils) for that. 

Here is [an article](https://levelup.gitconnected.com/easy-database-seeding-in-net-core-applications-f8bcc7a15112) that describes the whole process but it's not necessary to deep down into the DB initialization if you just want to run the sample and test EasyData. 

All "magic" occurs in `EnsureDbInitialized` method of `Startup` class. It creates the DB and seeds it with the data stored in EqDemoData.zip file.
We use a local version of SQL Server by default but you can change the database you want to work with by modifying just 2 lines of code (one in DbContext initialization in `ConfigureServices`, second - in `EnsureDbInitialized`). For example, to see your SQLite DB instead of SQL Server you will need to replace `UseSqlServer` call there with `UseSqLite`.

**Comment by korzh** [comment]
I guess we can close this issue for now
