### ISSUE TITLE
Попытался сделать тестовый проект чтобы посмотреть библиотеку, но копки добавить новую сущность не нашел

### ISSUE THREAD

**Issue by itrafory** [KorzhCom/EasyData#86]
![image](https://user-images.githubusercontent.com/84319506/148294664-010ed2b1-a8e6-47b7-8a45-e5c1ff1e81bf.png)
проект .net6  -> Asp.net Core Web  App -> Razor pages, скрипты версии 1.4.0

**Comment by korzh** [comment]
Does it happen only on empty tables or on any data set?

**Comment by itrafory** [comment]
any data, and I trying to run your samples and got the same result

**Comment by korzh** [comment]
There was an error with one CSS rule. We have fixed it and re-published the CSS file (easydata.min.css). 

So, the samples that use the CDN version of CSS (https://cdn.korzh.com/ed/1.4.0/easydata.min.css) must work well now and show that "add row" button [+] button in the grid's header row.

However, the problem still remains if you are using EasyData NPM packages. It will be fixed with the next update (version 1.4.1).

**Comment by itrafory** [comment]
I checked, first solution is work for me and at this moment it is enough for me.
Thanks for help
