### ISSUE TITLE
Custom entity list page

### ISSUE THREAD

**Issue by sanket-pattekar** [KorzhCom/EasyData#90]
Hi

I want to change and create a custom entity listing page. 

As I see in the current implementation, there is just a div with id "EasyDataContainer" in the index.cshtml. The javascript then make calls and appends the entities to this div. However, I want to display the entities in a grid with a view/edit button next to it. 

How to build this custom view utilizing the javascript and also the middleware

Sanket

**Comment by korzh** [comment]
Hello,

There are two main views in EasyData:  

* [RootDataView](https://github.com/KorzhCom/EasyData/blob/master/easydata.js/packs/crud/src/views/root_data_view.ts) is responsible for rendering the list of entities (tables) available in the data model (metadata). 

* [EntityDataView](https://github.com/KorzhCom/EasyData/blob/master/easydata.js/packs/crud/src/views/entity_data_view.ts) renders the table (grid) with all records for one selected entity (table).

So, currently, you can only rewrite these classes to change the look. I guess we can provide an easy mechanism of substitution of any of these view classes with custom-defined ones.

Is it what you asked for?

**Comment by sanket-pattekar** [comment]
First, let me thank for an excellent package. It is very easy to use and does achieve a lot of things. I want to use easydata for display/editing master data in my database.

There are 2 things that I need to achieve
1,  On the root page, I want to display the entities in Grid with a button to go to the details page.( I was able to achieve this using reflection on DBContext)
2. On the details page, I want to have differnt styles for the column header and also for the data. Also I do not want to display the search box. Can this be achieved ?

**Comment by korzh** [comment]
Hello,

Sorry for the late reply. We were quite busy here in Ukraine preparing to fight back against a possible Russian invasion. :)

Regarding your notes:

1. I don't quite understand how the described scenario is different from the one we have now in our sample projects. We usually have there one "root" page with a list of all entities (I believe it would be pretty easy to use a grid instead of a list there). When you click on the one item in that list - you open a details page with all CRUD operations for the selected entity.

2. It is also quite easy to set different styles for header and data. There are different CSS classes for the header cells and for data cells in the grid. So, you can get different styles by settings different options in those classes. 
As for the search box, we will add a possibility to hide it in the upcoming version 1.4.3 release.

**Comment by korzh** [comment]
We have added the `showFilterBox` option in version 1.4.3, so now you can use it as:

```
    new EasyDataViewDispatcher({
        showFilterBox: false
    }).run()
```
